import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  Text: {fontSize: 14, color: 'white', alignSelf: 'center'},
  Image: {
    height: 50,
    width: 50,
    alignSelf: 'center',
    borderRadius: 100,
    marginLeft: 16,
  },
  touchA: {
    width: 80,
    height: 29,
    borderRadius: 29,
    backgroundColor: '#60B939',
    marginTop: 20,
    marginRight: 16,
    justifyContent: 'center',
  },
  touchA1: {
    width: 95,
    height: 29,
    borderRadius: 29,
    marginTop: 20,
    
    backgroundColor: '#666666',
    marginRight: 16,
    justifyContent: 'center',
  },
  viewA: {
    flexDirection: 'row',
    height: 70,
    borderBottomWidth: 1,
    borderBottomColor: '#C4C4C4',
    justifyContent: 'space-between',
  },
  feel: {
    width: 100,
    height: 100,
    backgroundColor: '#E5E5E5',
    marginLeft: 14,
    borderRadius: 10,
  },
  baseText: {alignSelf: 'center', fontSize: 14,justifyContent:'center'},
  comment: {
    color: '#60B939',
    alignSelf: 'flex-start',
    marginTop: 20,
    fontSize: 14,
    marginLeft: 16,
  },
  Text1: {
    fontSize: 18,
    marginTop: 20,
    alignSelf: 'center',
    justifyContent: 'center',
    //  fontWeight:'bold',
    // marginLeft:16,
  },
  icon: {height: 60, width: 60, alignSelf: 'center', marginTop: 20},

  input: {
    height: 60,
    margin: 10,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    width: 360,
    borderColor: '#C4C4C4',
    marginLeft: 16,
    // marginRight: 16,
    marginTop: 15,
    backgroundColor: '#DFDCDC',
  },
  tichxanh: {widt: 24, height: 24, position: 'absolute', top: 70, left: 70},
  login: {
    backgroundColor: '#60B939',
        //color: 'white',
        height: 50,
        borderRadius: 10,
        marginTop: 32,
        marginLeft: 16,
        marginRight: 16,
        fontSize: 14,
        width: 328,
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
  },
});
export default styles;
