import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    //paddingTop: 50,
  },
  imageyes: {
    flexDirection: 'row',
    width: 24,
    height: 24,
    position: 'absolute',
    top: 30,
    right: 20,
  },
  Text1: {
    fontSize: 14,
    marginTop: 30,
    alignSelf: 'center',
    //fontWeight:'bold',
  },
  google1: {
    borderRadius: 16,
    height: 36,
    width: 36,
    //  alignSelf:'center',

  },
  facebook1: {
    borderRadius: 16,
    height: 36,
    width: 36,
    //  alignSelf:'center',
    marginLeft: 15,
  },
  input: {
    height: 50,
    margin: 10,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal:10,
    width: 384,
    borderColor: "#C4C4C4",
    marginLeft: 16,
    marginRight: 16,
    marginTop: 42,
  },
  input1: {
    height: 50,
    margin: 10,
    borderWidth: 1,
    borderRadius: 10,
    width: 384,
    borderColor: "#C4C4C4",
    paddingHorizontal:10,
    marginLeft: 16,
    marginRight: 16,
    marginTop: 18,
  },
  Text2: {
    fontSize: 14,
    marginTop: 18,
    alignSelf: 'center',
    //  fontWeight:'bold',
    marginLeft: 18,

  },
  imagee: {
    height: 49,
    width: 166,
    alignSelf: 'center',
    marginTop: 81,
    marginLeft: 97,
    marginRight: 97,
  },
  password: {
    fontWeight: 'bold',
    alignSelf: 'center',
    fontSize: 14,
    color: 'black',
    marginTop:25,
  },
  dangki: {
    color: '#60B939',
    fontSize: 14,
    //fontWeight: 'bold',
  },
  Text: {
    fontSize: 14,
    marginTop: 43,
    alignSelf: 'center',
    //fontWeight: 'bold',
    marginRight: 107,
    marginLeft: 107,
  },
  image: {
    height: 49,
    width: 166,
    alignSelf: 'center',
    marginLeft: 97,
    marginRight: 97,

    marginTop: 24,
  },
  google: {
    borderRadius: 16,
    height: 36,
    width: 36,
    //  alignSelf:'center',
    // marginLeft:10,
    bottom: '16.41%',
  },
  facebook: {
    borderRadius: 16,
    height: 36,
    width: 36,
    marginLeft: 15,
    //  alignSelf:'center',
    bottom: '16.41%',
  },
  login: {
    backgroundColor: '#60B939',
        //color: 'white',
        height: 50,
        borderRadius: 10,
        marginTop: 32,
        marginLeft: 16,
        marginRight: 16,
        fontSize: 14,
        width: 328,
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
  },
  baseText: {
    //fontWeight: 'bold',
    alignSelf: 'flex-end',
    marginRight: 16,
    fontSize: 14,
    marginTop: 18,
  },
  otp:{
    fontWeight:'bold',
    alignSelf:'center',
    fontSize: 14,
    color:'black',
    marginTop:25,
    //marginLeft:88,
  },
  send:{
   // fontWeight:'bold',
    alignSelf:'center',
    fontSize: 14,
    color:'#60B939',
    marginTop:18,
   // marginLeft:132,
  },
  under: {
    width: 18,
    height: 2,
    borderWidth: 0,
    borderBottomWidth: 1,
    color:'black',
    borderColor:'black'

  },

  underonclick: {
    borderColor: "red",
  },
  maotp:{
    width: 118,
     height: 29, 
     alignSelf:'center',
     marginTop:18,
  },
});
export default styles;